"""
Django settings for warehouse project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from celery.schedules import crontab
from django.utils.translation import gettext_lazy as _
from django.contrib.admin import AdminSite
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-gc^kgmae9483vd#k_gy1fq9rrd_e64r%g^*d8b#m1ys^u%*uti"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": lambda request: True,
    "IS_RUNNING_TESTS": True
}

################################################
#         Application Definition              #
################################################

INSTALLED_APPS = [
    # Django core apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'drf_spectacular',
    
    # Local apps
    'accounts.apps.AccountsConfig',
    'inventory.apps.InventoryConfig',
    'analytics.apps.AnalyticsConfig',
]

################################################
#         Middleware Configuration             #
################################################

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",  # CORS middleware - must be high
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",  # i18n middleware
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

################################################
#         URL Configuration                   #
################################################

ROOT_URLCONF = "warehouse.urls"

################################################
#         Templates Configuration             #
################################################

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',  # For i18n
            ],
        },
    },
]

################################################
#         WSGI Configuration                  #
################################################

WSGI_APPLICATION = "warehouse.wsgi.application"

################################################
#         Database Configuration              #
################################################

# warehouse/settings.py

DB_TYPE = os.getenv('DB_TYPE', 'sqlite')

if DB_TYPE != 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3'
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB'),
            'USER': os.getenv('POSTGRES_USER'),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
            'HOST': os.getenv('POSTGRES_HOST', 'postgres'),
            'PORT': os.getenv('POSTGRES_PORT'),
            'OPTIONS': {
                'options': '-c timezone=UTC'
            }
        }
    }
################################################
#         Password Validation                 #
################################################

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

################################################
#         Internationalization (i18n)         #
################################################

# Internationalization
LANGUAGE_CODE = 'en'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Supported languages
LANGUAGES = [
    ('en', _('English')),
    ('es', _('Español')),
    ("uk", _("Ukrainian")),
    ('ar', _('Arabic')),
]

# Bidirectional languages (Right-to-Left)
LANGUAGES_BIDI = ['ar']

# Path for translation files
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale')
]

################################################
#         Static & Media Files                #
################################################

STATIC_URL = '/static/'
STATIC = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)


################################################
#         Default Primary Key Field           #
################################################

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

################################################
#         Admin Interface Configuration       #
################################################

ADMIN_SITE_HEADER = "Warehouse Management System"
ADMIN_SITE_TITLE = "Warehouse Admin Portal"
ADMIN_INDEX_TITLE = "Dashboard Inventory Control"

AdminSite.site_header = ADMIN_SITE_HEADER
AdminSite.site_title = ADMIN_SITE_TITLE
AdminSite.index_title = ADMIN_INDEX_TITLE

################################################
#         Django REST Framework (DRF)         #
################################################

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
    ),
    'PAGE_SIZE': 20,
    'ORDERING_PARAM': 'ordering',
}

################################################
#         JWT Configuration                   #
################################################

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELDS': ['id', 'email']
}

################################################
#         Redis Cache Configuration           #
################################################

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://redis:6379/1',
        'TIMEOUT': 5 * 60,
        'KEY_PREFIX': 'warehouse'
    },
    'page_cache': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://redis:6379/1',
        'TIMEOUT': 15 * 60,
        'KEY_PREFIX': 'warehouse_page'
    }
}

################################################
#         Celery Configuration                #
################################################


CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')

# Celery settings
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_TASK_SOFT_TIME_LIMIT = 20 * 60  # 20 minutes
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 1000

# Celery Beat Schedule - Periodic tasks
CELERY_BEAT_SCHEDULE = {
    'generate-daily-report': {
        'task': 'inventory.tasks.generate_daily_inventory_report',
        'schedule': crontab(hour=0, minute=0),  # Daily at midnight
        'options': {'expires': 3600},  # Expires after 1 hour
    },
    'check-low-stock': {
        'task': 'inventory.tasks.check_all_low_stock',
        'schedule': crontab(hour='*/6', minute=0),  # Every 6 hours
        'options': {'expires': 1800},  # Expires after 30 minutes
    },
    'sync-with-projecta': {
        'task': 'inventory.tasks.sync_product_with_projecta',
        'schedule': crontab(hour=0, minute=30),  # Daily at 00:30
        'options': {'expires': 7200},  # Expires after 2 hours
    },
}

################################################
#         Logging Configuration               #
################################################

# warehouse/settings.py - Agregar al final del archivo

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime}  {name} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        'simple': {
            'format': '[{levelname}] {asctime} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S'
        },
        
        'json': {
            '()': 'pythonjsonlogger.jsonlogger.JsonFormatter',
            'format': '%(asctime)s %(name)s %(levelname)s %(module)s %(message)s',
        },
    },
    
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    
    'handlers': {
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file_all': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'all.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'error.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'file_django': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'django.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'file_db': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'database.log'),
            'maxBytes': 1024 * 1024 * 10,
            'backupCount': 10,
            'formatter': 'verbose',
            'filters': ['require_debug_true']
        },
    },
    
    'loggers': {
        
        '': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'INFO',
            'propagate': False
        },
        
        'django': {
            'handlers': ['console', 'file_django', 'file_error'],
            'level': 'DEBUG',
            'propagate': False
        },
        
        'django.request': {
            'handlers': ['file_error'],
            'level': 'ERROR',
            'propagate': False,
        },
        
        'django.db.backends': {
            'handlers': ['file_db'],
            'level': 'DEBUG',
            'propagate': False
        },
        
        'accounts': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'DEBUG',
            'propagate': False
        },
        'inventory': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'DEBUG',
            'propagate': False
        },
        'analytics': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'DEBUG',
            'propagate': False
        },
        'middleware': {
            'handlers': ['console', 'file_all', 'file_error'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
################################################
#         Spectacular API (Swagger)           #
################################################

SPECTACULAR_SETTINGS = {
    'TITLE': 'Warehouse Management API',
    'DESCRIPTION': 'API for ProjectB Warehouse Service - Inventory, Analytics, and Stock Management',
    'VERSION': 'v1',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
    },
    'REDOC_SETTINGS': {
        'lazyRendering': True,
    },
}

################################################
#         ProjectA Communication              #
################################################

# ProjectA URL for inter-service communication
PROJECTA_URL = os.getenv('PROJECTA_URL', 'http://localhost:8000')
PROJECTA_API_USER = os.getenv('PROJECTA_API_USER', 'warehouse_service')
PROJECTA_API_PASSWORD = os.getenv('PROJECTA_API_PASSWORD', '')

###################################################
#               SENTRY-CONF                       #
###################################################


import sentry_sdk
import logging
from sentry_sdk.integrations.django import DjangoIntegration
from sentry_sdk.integrations.logging import LoggingIntegration
from sentry_sdk.integrations.celery import CeleryIntegration
from sentry_sdk.integrations.redis import RedisIntegration

IS_GITHUB_ACTIONS = os.getenv('GITHUB_ACTIONS') == 'true'
if not IS_GITHUB_ACTIONS:
    sentry_sdk.init(
        dsn="https://e8ee2e86546a8fb43a84be2a30ebf57a@o4511450103545856.ingest.de.sentry.io/4511450364444752",
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(
                event_level=logging.ERROR
            ),
            CeleryIntegration(),
            RedisIntegration()
        ],
        attach_stacktrace=True,
        environment='development' if DEBUG else 'production-project',
        send_default_pii=True,
    )

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8080',
    'https://localhost:8443',
    'http://127.0.0.1:8080',
    'https://127.0.0.1:8443',
    'https://192.168.1.3:8443',
]
